services:
  php:
    container_name: php_elderly-travel
    build: .
    volumes:
      - ./src:/var/www/html/
    networks:
      - web_network
      
  nginx:
    container_name: nginx_elderly-travel
    image: nginx:alpine
    volumes:
      - ./src:/var/www/html/:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/snippets/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    depends_on:
      - php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elderly-travel.entrypoints=web"
      - "traefik.http.routers.elderly-travel.rule=Host(`elderly-travel.aklkbqx.xyz`)"
      - "traefik.http.services.elderly-travel.loadbalancer.server.port=80"
    networks:
      - web_network

networks:
  web_network:
    external: true
